GET http://localhost:8080/spring-mvc-app/api/v1/product/7
Authorization: Basic mem_user pass

###

GET http://localhost:8080/spring-mvc-app/api/v1/product/all
Authorization: Basic mem_user pass
###

POST http://localhost:8080/spring-mvc-app/api/v1/product
Authorization: Basic admin qwe123
Content-Type: application/json

{
  "name": "create by rest1",
  "price": 34.00
}

###

PUT http://localhost:8080/spring-mvc-app/api/v1/product
Content-Type: application/json

{
  "id": 11,
"name": "create by rest",
"price": 333.00
}

###

DELETE http://localhost:8080/spring-mvc-app/api/v1/product/11